# Site wide configuration

title: 大灰狼窝
description: 另一个垃圾桶
logo: http://assilzm.github.io/images/1506245.jpg
teaser: # 400x250 px default teaser image used in image archive grid
locale:
url: http://www.assilzm.com

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:assilzm
  name:assilzm
  email:assilzm@gmail.com
  twitter:assilzm
  google:assilzm
    ad-client:
    ad-slot:
  bio:
  avatar: bio-photo.jpg # 160x160 px image for author byline
disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
