# General
name: 大灰狼窝
description: "另一个垃圾桶"
url: http://assilzm.github.io

markdown: redcarpet
highlighter: pygments

paginate: 5
permalink: /:title

# Social share and comments.
twitter: assilzm
github: assilzm
google: +assilzm

# RSS feed
rss-feed-limit: 10
rss-show-full: "no"
